---
title: "Appendix A with quantile regression"
author: "Remko Duursma"
date: "12 October 2017"
output: word_document
---

```{r params, echo=FALSE}
# Choice of quantiles
quants <- seq(0.05, 1, by=0.05)

# Whether to shade areas between quantiles
# (works best when using only three quantiles)
shade_quants <- FALSE

# Whether to add labels to the lines
label_quants <- FALSE

```



```{r load, include=FALSE}
library(dplyr)
library(magicaxis)
library(quantreg)
library(scales)

library(extrafont)
#loadfonts(device="win")

library(knitr)


knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, dpi=300,
                      fig.width=6.7, fig.height=6.7)

# Plot polygon in between two quantile fits
poly_rqs <- function(mod1, mod2, ...){
  
  pu <- par("usr")
  x <- pu[1:2]
  
  newdat <- data.frame(volume=10^x)
  y1 <- predict(mod1, newdata=newdat)
  y2 <- predict(mod2, newdata=newdat)
  
  polygon(x=c(x, rev(x)), y=c(y1, rev(y2)), border=NA, ...)
}

# Tree-level data
sitree <- read.csv("data/si_climate.csv") %>%
  dplyr::select(volume, sizeindex, leaf_type) %>%
  rename(si = sizeindex) %>%
  filter(volume >= 18)

sitree_small_ever <- filter(sitree, volume < 100, leaf_type=="evergreen")
sitree_small_deci <- filter(sitree, volume < 100, leaf_type=="deciduous")
sitree_large <- filter(sitree, volume >= 100)
```



```{r}
plot_si_ranges <- function(fits, whichfits=1:length(fits), xlim, ylim, 
                           labsrt=30,
                           labyadj=0,
                           plot_lab=TRUE,
                           quantiles = c(0.05,0.1,0.25,0.75,0.9,0.95),
                           plot_poly=TRUE,
                           poly_colors = c("grey95", "lightgrey","grey", 
                                           "lightgrey", "grey95"),
                           plot_data=NULL,
                           ...){

  fits <- fits[whichfits]
  
  xat <- as.vector(sapply(1:3, function(i)seq(10^i, 10^(i + 1) - 10^i, by=10^i)))
  yat <- as.vector(sapply(0:3, function(i)seq(10^i, 10^(i + 1) - 10^i, by=10^i)))

  par(yaxs="i", xaxs="i", las=1, tcl=0, cex.lab=1.2, 
      mgp=c(2.4, 0.25, 0), 
      cex.axis=0.7, pty='s',
      family="Gotham Narrow Book")

  plot(1, pch=16, cex=0.5, 
                        type='n',
                        panel.first={
                          abline(v=log10(xat), col="grey")
                          abline(h=log10(yat), col="grey")
                          
                          if(plot_poly){
                            for(i in 1:(length(fits)-1)){
                              poly_rqs(fits[[i]], fits[[i+1]], 
                                       col=alpha(poly_colors[i], 0.6))
                            }
                          }
                          
                          if(!is.null(plot_data)){
                            with(plot_data, points(log10(volume), log10(si), pch=16, 
                                              col="grey", cex=0.5))
                          }

                        },
                        ylim=ylim,
                        xlim=xlim,
                        xlab="Container Volume (L)",
                        ylab="Size Index (calliper x height)",
                  col="darkgrey", axes=FALSE)
  for(i in 1:length(fits))abline(fits[[i]], lty=2, lwd=1)
  
  axis(1, at=log10(xat), labels=xat)
  axis(2, at=log10(yat), labels=yat)
  box()
  
  if(plot_lab){
    u <- par("usr")
    xat <- u[1] + 0.2*(u[2] - u[1])
    y <- sapply(fits, function(x)predict(x, newdata=data.frame(volume = 10^xat)))
    labs <- paste0(100*quantiles, "%")
    text(xat, y+labyadj, labs, pos=2, font=2, cex=0.8, srt=labsrt)
    
    xat <- u[1] + 0.5*(u[2] - u[1])
    y <- sapply(fits, function(x)predict(x, newdata=data.frame(volume = 10^xat)))
    y <- y[1:(length(y)-1)] + diff(y)/2
    labs <- c("Small","Medium","Large")
    text(xat, y, labs, pos=2, font=2, cex=1.1, srt=labsrt, col="dimgrey")
  }

}


make_si_plot <- function(data, quantiles, ...){
  
  fits <- lapply(quantiles, function(x)rq(log10(si) ~ log10(volume), data=data, tau=x))
  
  plot_si_ranges(fits, 
                 poly_colors=c("lightgrey","grey","lightgrey"),
                 quantiles=quantiles, ...)

}

```


# Evergreen trees (<100L)

Dashed lines are quantile regression fits, from 5% (lowest line) to 100% (top line), in steps of 5%.

```{r}
make_si_plot(sitree_small_ever,
             quantiles=quants,
             plot_poly=shade_quants,
             plot_lab=label_quants,
             labyadj=-0.05, 
             xlim=log10(c(18,100)), 
             ylim=log10(c(8,250)), labsrt=30)
```



# Deciduous trees (<100L)

Dashed lines are quantile regression fits, from 5% (lowest line) to 100% (top line), in steps of 5%.

```{r}
make_si_plot(sitree_small_deci,
             quantiles=quants,
             plot_poly=shade_quants,
             plot_lab=label_quants,
             labyadj=-0.04, 
            xlim=log10(c(18,100)), ylim=log10(c(8,250)), labsrt=22)
```


# Large containers (>100L)

Dashed lines are quantile regression fits, from 5% (lowest line) to 100% (top line), in steps of 5%.

```{r}
make_si_plot(sitree_large,
             quantiles=quants,
             plot_poly=shade_quants,
             plot_lab=label_quants,
             labyadj=-0.06, 
             xlim=log10(c(100,3000)), ylim=log10(c(50,3000)), labsrt=34)
```







```{r make_tables, eval=FALSE}
# Tables


quantiles <- c(0.05,0.1,0.25,0.75,0.9,0.95)
fit_small_ever <- lapply(quantiles, 
                         function(x)rq(log10(si) ~ log10(volume), data=sitree_small_ever, tau=x))

fit_small_deci <- lapply(quantiles, 
                         function(x)rq(log10(si) ~ log10(volume), data=sitree_small_deci, tau=x))

fit_large <- lapply(quantiles, 
                         function(x)rq(log10(si) ~ log10(volume), data=sitree_large, tau=x))



vols <- sort(unique(sitree$volume))

vols_small <- vols[vols < 100]
vols_large <- vols[vols >= 100]

tab_large <- cbind(data.frame(volume=vols_large),
                   as.data.frame(sapply(fit_large, function(x)10^predict(x, newdata=data.frame(volume=vols_large))))
)
names(tab_large) <- c("volume", paste0(100*quantiles, "%"))

tab_small_deci <- cbind(data.frame(volume=vols_small),
                   as.data.frame(sapply(fit_small_deci, function(x)10^predict(x, newdata=data.frame(volume=vols_small))))
)
names(tab_small_deci) <- c("volume", paste0(100*quantiles, "%"))

tab_small_ever <- cbind(data.frame(volume=vols_small),
                   as.data.frame(sapply(fit_small_ever, function(x)10^predict(x, newdata=data.frame(volume=vols_small))))
)
names(tab_small_ever) <- c("volume", paste0(100*quantiles, "%"))



```


```{r, eval=FALSE}
## Small, deciduous

knitr::kable(round(tab_small_deci,0))
```



```{r, eval=FALSE}
## Small, evergreen

knitr::kable(round(tab_small_ever,0))
```




```{r, eval=FALSE}
## Large

knitr::kable(round(tab_large,0))
```





